### ISSUE TITLE
I can contribute for TogetherOS, apply for join and hope contribution.

### ISSUE THREAD

**Issue by ImproveEvery** [TogetherOS/JoinRequest#58]
**Write your GitHub username:**tisonkong
i write some tech blogs in JianShu：https://www.jianshu.com/u/abcf0e8f851a.
i create and update my Java knowledge in this website, i can make contributions for TOS in my sparetime

**Comment by crossoverJie** [comment]
已邀

**Comment by ImproveEvery** [comment]
Thanks， I will try my best to improve
